# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_data.proto',
  package='posepair',
  syntax='proto3',
  serialized_options=_b('\n\023cmu.posepair.protosB\rPosePairProtoP\001\242\002\003PPP'),
  serialized_pb=_b('\n\x11sensor_data.proto\x12\x08posepair\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n\x0eWatchDataBlock\x12\x10\n\x08watch_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x46_samp\x18\x02 \x01(\x02\x12,\n\x08t_latest\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nlinAccel_x\x18\x04 \x03(\x02\x12\x12\n\nlinAccel_y\x18\x05 \x03(\x02\x12\x12\n\nlinAccel_z\x18\x06 \x03(\x02\"}\n\tHumanPose\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12%\n\x01t\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05pos_x\x18\x03 \x03(\x02\x12\r\n\x05pos_y\x18\x04 \x03(\x02\x12\x18\n\x10joint_confidence\x18\x05 \x03(\x02\x32\xa1\x01\n\x12SensorDataReceiver\x12G\n\x0fStreamWatchData\x12\x18.posepair.WatchDataBlock\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12\x42\n\x0fStreamHumanPose\x12\x13.posepair.HumanPose\x1a\x16.google.protobuf.Empty\"\x00(\x01\x42,\n\x13\x63mu.posepair.protosB\rPosePairProtoP\x01\xa2\x02\x03PPPb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_WATCHDATABLOCK = _descriptor.Descriptor(
  name='WatchDataBlock',
  full_name='posepair.WatchDataBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='watch_id', full_name='posepair.WatchDataBlock.watch_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='F_samp', full_name='posepair.WatchDataBlock.F_samp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_latest', full_name='posepair.WatchDataBlock.t_latest', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linAccel_x', full_name='posepair.WatchDataBlock.linAccel_x', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linAccel_y', full_name='posepair.WatchDataBlock.linAccel_y', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linAccel_z', full_name='posepair.WatchDataBlock.linAccel_z', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=250,
)


_HUMANPOSE = _descriptor.Descriptor(
  name='HumanPose',
  full_name='posepair.HumanPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person_id', full_name='posepair.HumanPose.person_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t', full_name='posepair.HumanPose.t', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='posepair.HumanPose.pos_x', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='posepair.HumanPose.pos_y', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='joint_confidence', full_name='posepair.HumanPose.joint_confidence', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=377,
)

_WATCHDATABLOCK.fields_by_name['t_latest'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_HUMANPOSE.fields_by_name['t'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['WatchDataBlock'] = _WATCHDATABLOCK
DESCRIPTOR.message_types_by_name['HumanPose'] = _HUMANPOSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WatchDataBlock = _reflection.GeneratedProtocolMessageType('WatchDataBlock', (_message.Message,), dict(
  DESCRIPTOR = _WATCHDATABLOCK,
  __module__ = 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:posepair.WatchDataBlock)
  ))
_sym_db.RegisterMessage(WatchDataBlock)

HumanPose = _reflection.GeneratedProtocolMessageType('HumanPose', (_message.Message,), dict(
  DESCRIPTOR = _HUMANPOSE,
  __module__ = 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:posepair.HumanPose)
  ))
_sym_db.RegisterMessage(HumanPose)


DESCRIPTOR._options = None

_SENSORDATARECEIVER = _descriptor.ServiceDescriptor(
  name='SensorDataReceiver',
  full_name='posepair.SensorDataReceiver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=380,
  serialized_end=541,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamWatchData',
    full_name='posepair.SensorDataReceiver.StreamWatchData',
    index=0,
    containing_service=None,
    input_type=_WATCHDATABLOCK,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamHumanPose',
    full_name='posepair.SensorDataReceiver.StreamHumanPose',
    index=1,
    containing_service=None,
    input_type=_HUMANPOSE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORDATARECEIVER)

DESCRIPTOR.services_by_name['SensorDataReceiver'] = _SENSORDATARECEIVER

# @@protoc_insertion_point(module_scope)
